---
title: "Hyperparameter Tuning"
author: "Ng Wei Keat, 20793486"
output: github_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, echo = TRUE, dpi = 180, fig.width = 8, fig.height = 5)
library(tidyverse)
```

## Explore data

```{r}
library(tidyverse)

food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
```


```{r}
library(countrycode)

food <- food_consumption %>%
  mutate(continent = countrycode(country, 
                                 origin = "country.name", 
                                 destination = "continent")) %>%
  select(-co2_emmission) %>%
  pivot_wider(names_from = food_category, values_from = consumption) %>%
  janitor::clean_names() %>%
  mutate(asia = case_when(continent == "Asia" ~ "Asia", TRUE ~ "Other")) %>%
  select(-country, -continent) %>%
  mutate_if(is.character, factor)
  
```

```{r}
library(GGally)

ggscatmat(food, columns = 1:11, color = "asia", alpha = 0.6)
```


## Tune hyperparameters

```{r}
library(tidymodels)
set.seed(20793486)
food_boot <- bootstraps(food, times = 30)

rf_spec <- rand_forest(mode = "classification",
            mtr = tune(), trees = 1000, min_n = tune()) %>%
  set_engine("ranger")

rf_grid <- tune_grid(
  asia ~.,
  model = rf_spec,
  resamples = food_boot
)

```


```{r}
rf_grid %>%
  collect_metrics()

rf_grid %>%
  show_best("roc_auc")
```


Can use parallel processing to speed this up!!








