---
title: "Inferential Statistics (Vaccination Rates)"
author: "Ng Wei Keat, 20793486"
output: github_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, echo = TRUE, dpi = 180, fig.width = 8, fig.height = 5)
library(tidyverse)
```

## Explore Data

```{r}
library(tidyverse)

measles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-25/measles.csv')

measles_df <- measles %>%
  filter(mmr > 0) %>%
  transmute(state, 
            mmr_threshold = case_when(mmr > 95 ~ "Above", TRUE ~ "Below")) %>%
  mutate_if(is.character, factor)
```

```{r}
library(skimr)
skim(measles_df)
```

```{r}
measles_df %>%
  group_by(state) %>%
  summarise(mmr = mean(mmr_threshold == "Above")) %>%
  mutate(state = fct_reorder(state, mmr)) %>%
  ggplot(aes(state, mmr, fill = state)) +
  geom_col(show.legend = FALSE) +
  scale_y_continuous(labels = scales::percent_format()) +
  coord_flip()
```

## Getting Started with Tidymodels

```{r}
library(tidymodels)

glm_fit <- logistic_reg() %>%
  set_engine("glm") %>%
  fit(mmr_threshold ~ state, data = measles_df)

tidy(glm_fit)
```

```{r}
new_schools <- tibble(state = unique(measles_df$state))

mean_pred <- predict(glm_fit, new_data = new_schools, type = "prob")

conf_int <- predict(glm_fit, new_data = new_schools, type = "conf_int")

schools_result <- new_schools %>%
  bind_cols(mean_pred) %>%
  bind_cols(conf_int)

```

```{r}
schools_result %>%
  mutate(state = fct_reorder(state, .pred_Above)) %>%
  ggplot(aes(state, .pred_Above, fill = state)) +
  geom_col(show.legend = FALSE) +
  geom_errorbar(aes(ymin = .pred_lower_Above,
                    ymax  = .pred_upper_Above), color = "gray30") +
  scale_y_continuous(labels = scales::percent_format()) +
  coord_flip()
```


## Trying another model

```{r}
library(rstanarm)
options(mc.cores = parallel::detectCores())

prior_dist <- student_t(df = 2)

stan_fit <- logistic_reg() %>%
  set_engine("stan", prior = prior_dist, prior_intercept = prior_dist) %>%
  fit(mmr_threshold ~ state, data = measles_df)
```

```{r}
bayes_pred <- predict(stan_fit, new_data = new_schools, type = "prob")

bayes_int <- predict(stan_fit, new_data = new_schools, type = "conf_int")

bayes_result <- new_schools %>%
  bind_cols(bayes_pred) %>%
  bind_cols(bayes_int)

```

```{r}
schools_result %>%
  mutate(model = "glm") %>%
  bind_rows(bayes_result %>%
              mutate(model = "stan")) %>%
  mutate(state = fct_reorder(state, .pred_Above)) %>%
  ggplot(aes(state, .pred_Above, color = model)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymin = .pred_lower_Above,
                    ymax  = .pred_upper_Above),
                
                size = 1.5, alpha = 0.7) +
  scale_y_continuous(labels = scales::percent_format()) +
  coord_flip()
```

Can use dodge to differentiate between the overlaid plots!!

