---
title: "Topic Modeling"
author: "Ng Wei Keat, 20793486"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data download and prep

```{r}
library(gutenbergr)
library(dplyr)
library(tidyr)
library(stringr)
library(tidytext)

sherlock_raw <- gutenberg_download(1661)

sherlock <- sherlock_raw %>%
  mutate(story = ifelse(str_detect(text, "ADVENTURE"), text, NA) ) %>%
  fill(story) %>%
  filter(story != "THE ADVENTURES OF SHERLOCK HOLMES") %>%
  mutate(story = factor(story, levels = unique(story)))

tidy_sherlock <- sherlock %>%
  mutate(line = row_number()) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  filter(word != "holmes")
```

## Explore tf-idf

```{r}
library(ggplot2)

tidy_sherlock %>%
  count(story, word, sort = TRUE) %>%
  bind_tf_idf(word, story, n) %>%
  group_by(story) %>%
  top_n(10) %>%
  ungroup %>%
  mutate(word = reorder(word, tf_idf)) %>%
  ggplot(aes(word, tf_idf), fill = story) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~story, scales = "free") +
  coord_flip()
```

## Implement topic modeling

```{r}
library(stm)
library(quanteda)

sherlock_dfm <- tidy_sherlock %>%
  count(story, word, sort = TRUE) %>%
  cast_dfm(story, word, n)

topic_model <- stm(sherlock_dfm, K = 6, init.type = "Spectral")
summary(topic_model)
```

```{r}
td_beta <- tidy(topic_model)

td_beta %>%
  group_by(topic) %>%
  top_n(10) %>%
  ungroup %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = topic)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~topic, scales = "free") +
  coord_flip()

td_gamma <- tidy(topic_model, matrix = "gamma",
                 document_names = rownames(sherlock_dfm))

ggplot(td_gamma, aes(gamma, fill = as.factor(topic))) +
  geom_histogram(show.legend = FALSE) + 
  facet_wrap(~topic, ncol = 3)
```

